### PR TITLE
Create simple flake definition

### LINKED ISSUE #49: Provide default.nix or flake.nix
This should only be a tiny wrapper around requirements.nix to follow the convention.

Motivated by the discussion in https://github.com/NixOS/nixos-homepage/issues/443

### PR DESCRIPTION
**Pull request by edibopp**
Resolves #49

### CODE REVIEW

**Comment by edibopp** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by edibopp** [comment]
recheckcla

**Comment by domenkozar** [comment]
CLA bot needs an update, but it works regardless of check failing.

**Comment by domenkozar** [comment]
Thank you!

**Pull request merged**
